apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: django-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`api.{{ cookiecutter.domain_name }}`)
      priority: 10
      services:
        - name: django
          port: 8000
  tls:
    secretName: cluster-cert-tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: k8s-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`k8s.{{ cookiecutter.domain_name }}`)
      priority: 10
      services:
        - name: django
          port: 8000
  tls:
    secretName: cluster-cert-tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http-to-https-redirect
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      priority: 1
      middlewares:
        - name: redirect-to-https
      services:
        - kind: TraefikService
          name: noop@internal
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
