apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  USE_DOCKER: "yes"
  DJANGO_ADMIN_URL: "^admin/"
  DJANGO_SETTINGS_MODULE: "config.settings.local"
  DJANGO_SECRET_KEY: "CHANGEME"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,django,{{ cookiecutter.domain_name }}"
  DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost,https://{{ cookiecutter.domain_name }}"
  DJANGO_SECURE_SSL_REDIRECT: "False"
  POSTGRES_DB: "sixiedb"
  POSTGRES_USER: "sixieuser"
  POSTGRES_PASSWORD: "CHANGEME"
  PGDATA: "/var/lib/postgresql/data/pgdata"
  DATABASE_URL: "psql://sixieuser:CHANGEME@postgres:5432/sixiedb"
  REDIS_URL: "redis://redis:6379/1"
  {%- if cookiecutter.use_celery == "y" %}
  CELERY_BROKER_URL: "redis://redis:6379/0"
  FLOWER_BROKER_URL: "redis://redis:6379/0"
  FLOWER_ADDRESS: "0.0.0.0"
  FLOWER_PORT: "5555"
  {%- endif %}
